server:
  port: 8087
spring:
  application:
    name: nacos-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: aliyun_route
          uri: lb://spring/cloud/test
          predicates:
            - Path=/gateway/sentinel/yml/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.01:3306/user?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5 #连接池空闲连接的最小数量。默认10
      maximum-pool-size: 15 #连接池中允许的最大连接数。默认10；
      auto-commit: true #自动提交从池中返回的连接。默认true
      login-timeout: 500
      idle-timeout: 60000 #一个连接闲置的最大时长（毫秒）。默认10分钟
      pool-name: Tata-HikariCP #连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
      validation-timeout: 3000 #验证连接有效性的超时时间（毫秒）
      max-lifetime: 120000 #一个连接在池中最长生命周期（毫秒），超时而且没被使用则被释放 默认30分钟。建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数
      connection-timeout: 60000 #数据库连接超时时间（毫秒）。默认30秒
      connection-test-query: select 1 from dual

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always